[package]
name = "substrate-ros-api"
version = "0.5.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
hex = "0.4"
rosrust = "0.9"
futures = "0.3"
futures-timer = "3"
serde_json = "1.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }

sp-api = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-core = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-session = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-chain-spec = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-state-machine = { git = "https://github.com/airalab/substrate", branch = "master" }

sc-rpc = { git = "https://github.com/airalab/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/airalab/substrate", branch = "master" }
sc-network = { git = "https://github.com/airalab/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/airalab/substrate", branch = "master" }

msgs = { package = "substrate-ros-msgs", path = "../msgs" }
