[package]
name = "robonomics-service"
version = "1.8.2"
authors = ["Airalab <research@aira.life>"]
description = "Robonomics node console line interface."
build = "build.rs"
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/airalab/robonomics"

[dependencies]
# third-party dependencies
clap = { version = "3.0", features = ["derive"], optional = true }
serde = { version = "1.0.130", features = ["derive"]}
codec = { package = "parity-scale-codec", version = "2.3" }
jsonrpc-core = { version = "18.0.0", optional = true }
hex-literal = "0.3.1"
log = "0.4"
parking_lot = "0.11.1"

# primitives
robonomics-primitives = { path = "../../../primitives", default-features = false }
robonomics-protocol = { path = "../../../protocol", default-features = false }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-transaction-storage-proof = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-tasks = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# client dependencies
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-informant = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", default-features = false }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-executor-common = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# frame dependencies
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
pallet-robonomics-lighthouse = { path = "../../../frame/lighthouse", optional = true }
pallet-robonomics-datalog = { path = "../../../frame/datalog", default-features = false }

# cumulus dependencies
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-client-consensus-common = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-client-consensus-relay-chain = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-relay-chain-local = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-relay-chain-interface = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-client-collator = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-client-network = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.17", optional = true }

# polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17", optional = true }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17", optional = true }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17", optional = true }

# node-specific dependencies
robonomics-rpc = { path = "../rpc", optional = true }
local-runtime = { path = "../../../runtime/local", optional = true }
alpha-runtime = { path = "../../../runtime/alpha", optional = true }
main-runtime = { path = "../../../runtime/main", optional = true }
ipci-runtime = { path = "../../../runtime/ipci", optional = true }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }

# Robonomics-specific dependencies
#robonomics-cli = { path = "../../../cli", optional = true }

[build-dependencies]
local-runtime = { path = "../../../runtime/local", optional = true }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.17", optional = true }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", optional = true }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
#robonomics-cli = { path = "../../../cli", optional = true }
vergen = { version = "3.1.0", optional = true }
clap = { version = "3.0", features = ["derive"], optional = true }
clap_complete = { version = "3.0", optional = true }

[features]
## Build fully functional node by default.
default = ["full"]

## Fully functional Robonomics Network node.
# Full node required for collating / validating the parachain or develop Robonomics pallets.
full = [
    "sc-cli",
    "sp-core",
    "vergen",
    "clap",
    "clap_complete",
    "local-runtime",
    "sc-service/db",
    "robonomics-rpc",
    "frame-benchmarking",
#    "robonomics-cli",
]

## Ultra lightweight Robonomics Network node.
# Stateless node consumes a minimum of resources and suits for small embedded devices.
zero = [
    "sc-cli",
    "sp-core",
    "vergen",
    "clap",
    "clap_complete",
#    "robonomics-cli",
]

## Enable Kusama parachain.
kusama = [
    "main-runtime",
    "parachain",
]

## Enable IPCI parachain.
ipci = [
    "ipci-runtime",
    "parachain",
]

## Enable parachain collator.
parachain = [
    "alpha-runtime",
    "pallet-robonomics-lighthouse",
    "substrate-frame-rpc-system",
    "jsonrpc-core",
    "cumulus-primitives-core",
    "cumulus-primitives-parachain-inherent",
    "cumulus-client-consensus-aura",
    "cumulus-client-consensus-common",
    "cumulus-client-consensus-relay-chain",
    "cumulus-relay-chain-interface",
    "cumulus-relay-chain-local",
    "cumulus-client-collator",
    "cumulus-client-network",
    "cumulus-client-service",
    "polkadot-primitives",
    "polkadot-parachain",
    "polkadot-service",
    "polkadot-cli",
    "full",
]

## Enable Wasmtime for runtime execution.
wasmtime = [
    "sc-service/wasmtime",
    "sc-cli/wasmtime",
]

## Enable ROS integration: exports to ROS topics and services for Robonomics communication.
# To build with it install ROS (http://wiki.ros.org/melodic/Installation) before.
# It also require roscore service to be launched.
ros = []

## Enable runtime benchmarking.
runtime-benchmarks = [
    "local-runtime/runtime-benchmarks",
    "frame-benchmarking-cli",
    "frame-benchmarking",
    "pallet-robonomics-datalog/runtime-benchmarks",
]
