[package]
name = "robonomics-io"
description = "Robonomics framework I/O operations."
version = "0.6.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
robonomics-protocol = { path = "../protocol" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
futures-timer = "3.0"
derive_more = "0.99"
serialport = "3.3"
async-std = "1.5"
ipfs-api = "0.7.1"
futures = "0.3.5"
sds011 = "0.1.4"
tokio = "0.2.21"
serde = "1.0.106"
log = "0.4"

# ROS integration 
substrate-ros-msgs = { path = "../../substrate-ros/msgs", optional = true }
rosrust = { version = "0.9", optional = true }

[features]
default = []
# Enable ROS features
ros = [
    "substrate-ros-msgs",
    "rosrust",
]
