[package]
name = "robonomics-cli"
description = "Robonomics Framework console line interfaces."
version = "0.5.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
robonomics-protocol = { path = "../protocol" }
robonomics-io = { path = "../io" }
derive_more = "0.99.11"
structopt = "0.3.8"
async-std = "1.7.0"
actix-rt = "1.1.1"
futures = "0.3.4"
serde_json = "1.0.0"
bincode = "1.3.1"
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master" }
log = "0.4.11"
hex = "0.4.2"
csv = "1.1.5"

[features]
default = []
ros = [
    "robonomics-io/ros",
]
