[package]
name = "robonomics-cli"
description = "Robonomics Framework console line interfaces."
version = "0.3.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
robonomics-protocol = { path = "../protocol" }
robonomics-io = { path = "../io" }
derive_more = "0.99"
structopt = "0.3.8"
async-std = "1.5"
futures = "0.3.4"
serde_json = "1.0"
bincode = "1.2"
sc-cli = "0.8.0-rc2"
log = "0.4"
hex = "0.4"
csv = "1.1"
