[package]
name = "robonomics-parachain-runtime"
version = "0.19.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
lazy_static = { version = "1.4", optional = true }
hex-literal = "0.2"

# primitives
node-primitives = { path = "../../primitives", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }

# frame dependencies
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-generic-asset = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" , default-features = false }
pallet-robonomics-launch = { path = "../../../../robonomics/frame/launch", default-features = false }
pallet-robonomics-datalog = { path = "../../../../robonomics/frame/datalog", default-features = false }
pallet-robonomics-liability = { path = "../../../../robonomics/frame/liability", default-features = false }

# cumulus dependencies
cumulus-runtime = { git = "https://github.com/paritytech/cumulus", default-features = false }
cumulus-parachain-upgrade = { git = "https://github.com/paritytech/cumulus", default-features = false }

[build-dependencies]
substrate-wasm-builder-runner = "1.0.6"

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

[features]
default = ["std"]
std = [
    "codec/std",
    "lazy_static",
    "cumulus-runtime/std",
    "cumulus-parachain-upgrade/std",
    "pallet-collective/std",
    "pallet-elections-phragmen/std",
    "pallet-balances/std",
    "sp-api/std",
    "frame-executive/std",
    "pallet-generic-asset/std",
    "pallet-indices/std",
    "pallet-identity/std",
    "node-primitives/std",
    "sp-offchain/std",
    "sp-core/std",
    "pallet-randomness-collective-flip/std",
    "sp-std/std",
    "serde",
    "serde_derive",
    "sp-runtime/std",
    "sp-session/std",
    "pallet-sudo/std",
    "pallet-scheduler/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-utility/std",
    "pallet-treasury/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "sp-version/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "pallet-robonomics-datalog/std",
    "pallet-robonomics-liability/std",
]
