[package]
name = "substrate-ros-rpc"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
rosrust = "0.8"
serde_json = "1.0"
futures-timer = "0.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
futures01 = { package = "futures", version = "0.1" }
futures-preview = { version = "0.3.0-alpha.19", features = ["compat", "async-await"] }
msgs = { package = "substrate-ros-msgs", path = "../msgs" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate" }
service = { package = "substrate-service", git = "https://github.com/paritytech/substrate" }
network = { package = "substrate-network", git = "https://github.com/paritytech/substrate" }
keystore = { package = "substrate-keystore", git = "https://github.com/paritytech/substrate" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate" }
substrate-rpc = { package = "substrate-rpc", git = "https://github.com/paritytech/substrate" }
state-machine = { package = "substrate-state-machine", git = "https://github.com/paritytech/substrate" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
