[package]
name = "ipci-runtime"
version = "0.19.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
serde = { version = "1.0.106", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.4", optional = true }
hex-literal = "0.2"

# primitives
node-primitives = { path = "../primitives", default-features = false }
sp-core = { version = "2.0.0-rc5", default-features = false }
sp-runtime = { version = "2.0.0-rc5", default-features = false }
sp-staking = { version = "2.0.0-rc5", default-features = false }
sp-consensus-babe = { version = "0.8.0-rc5", default-features = false }
sp-offchain = { version = "2.0.0-rc5", default-features = false }
sp-authority-discovery = { version = "2.0.0-rc5", default-features = false }
sp-api = { version = "2.0.0-rc5", default-features = false }
sp-inherents = { version = "2.0.0-rc5", default-features = false }
sp-block-builder = { version = "2.0.0-rc5", default-features = false }
sp-transaction-pool = { version = "2.0.0-rc5", default-features = false }
sp-std = { version = "2.0.0-rc5", default-features = false }
sp-version = { version = "2.0.0-rc5", default-features = false }
sp-session = { version = "2.0.0-rc5", default-features = false }

# frame dependencies
pallet-authorship = { version = "2.0.0-rc5", default-features = false }
pallet-authority-discovery = { version = "2.0.0-rc5", default-features = false }
pallet-babe = { version = "2.0.0-rc5", default-features = false }
pallet-balances = { version = "2.0.0-rc5", default-features = false }
frame-executive = { version = "2.0.0-rc5", default-features = false }
pallet-finality-tracker = { version = "2.0.0-rc5", default-features = false }
pallet-grandpa = { version = "2.0.0-rc5", default-features = false }
pallet-im-online = { version = "2.0.0-rc5", default-features = false }
pallet-indices = { version = "2.0.0-rc5", default-features = false }
pallet-identity = { version = "2.0.0-rc5", default-features = false }
pallet-offences = { version = "2.0.0-rc5", default-features = false }
pallet-offences-benchmarking = { version = "2.0.0-rc5", default-features = false, optional = true }
pallet-randomness-collective-flip = { version = "2.0.0-rc5", default-features = false }
pallet-session = { version = "2.0.0-rc5", default-features = false }
pallet-session-benchmarking = { version = "2.0.0-rc5", default-features = false, optional = true }
pallet-staking = { version = "2.0.0-rc5", default-features = false }
pallet-staking-reward-curve = "2.0.0-rc5"
pallet-sudo = { version = "2.0.0-rc5", default-features = false }
frame-support = { version = "2.0.0-rc5", default-features = false }
frame-benchmarking = { version = "2.0.0-rc5", default-features = false, optional = true }
frame-system = { version = "2.0.0-rc5", default-features = false }
frame-system-rpc-runtime-api = { version = "2.0.0-rc5", default-features = false }
frame-system-benchmarking = { version = "2.0.0-rc5", default-features = false, optional = true }
pallet-utility = { version = "2.0.0-rc5", default-features = false }
pallet-timestamp = { version = "2.0.0-rc5", default-features = false }
pallet-transaction-payment = { version = "2.0.0-rc5", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-rc5", default-features = false }
pallet-robonomics-datalog = { path = "../../../robonomics/frame/datalog", default-features = false }

[build-dependencies]
substrate-wasm-builder-runner = "1.0.6"

[dev-dependencies]
sp-io = "2.0.0-rc5"

[features]
default = ["std"]
std = [
    "codec/std",
    "lazy_static",
    "sp-authority-discovery/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "sp-consensus-babe/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "sp-api/std",
    "frame-executive/std",
    "pallet-finality-tracker/std",
    "pallet-grandpa/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-identity/std",
    "node-primitives/std",
    "sp-offchain/std",
    "pallet-offences/std",
    "sp-core/std",
    "pallet-randomness-collective-flip/std",
    "sp-std/std",
    "serde",
    "pallet-session/std",
    "sp-runtime/std",
    "sp-staking/std",
    "pallet-staking/std",
    "sp-session/std",
    "pallet-sudo/std",
    "frame-support/std",
    "frame-benchmarking/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "pallet-utility/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "sp-version/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "pallet-robonomics-datalog/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "sp-runtime/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-staking/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-session-benchmarking",
    "pallet-offences-benchmarking",
    "frame-system-benchmarking",
]
