[package]
name = "robonomics-rpc"
version = "1.0.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://robonomics.network"
repository = "https://github.com/airalab/robonomics" 

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0" }
jsonrpc-core = "15.1.0"
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
local-runtime = { path = "../../../runtime/local" }
robonomics-primitives = { path = "../../../primitives" }
