[package]
name = "robonomics-metadata"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Robonomics runtime metadata export utility"
readme = "README.md"

[lib]
name = "robonomics_metadata"
path = "src/lib.rs"

[dependencies]
robonomics-runtime = { workspace = true }
sp-io = { workspace = true }
sp-state-machine = { workspace = true }
sp-maybe-compressed-blob = { workspace = true }
sc-executor = { workspace = true }
sc-executor-common = { workspace = true }
parity-scale-codec = { workspace = true }
