[package]
name = "subkey"
version = "0.20.0"
authors = [
    "Parity Technologies <admin@parity.io>",
    "Airalab <research@aira.life>",
]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
futures = "0.1.29"
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
node-runtime = { package = "robonomics-runtime", path = "../node/robonomics-runtime" }
node-primitives = { path = "../node/primitives" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
rand = "0.7.2"
clap = "2.33.0"
tiny-bip39 = "0.7"
substrate-bip39 = "0.4.1"
hex = "0.4.0"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.1" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
rpassword = "4.0.1"
itertools = "0.8.2"
derive_more = { version = "0.99.2" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
jsonrpc-core-client = { version = "14.2.0", features = ["http"] }
hyper = "0.12.35"
libp2p = "0.22.0"
serde_json = "1.0"

[features]
bench = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
