[package]
name = "pallet-robonomics-datalog-xcm"
description = "XCM extension for data logging Substrate runtime module"
version = "0.3.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0", default-features = false, features = ["derive"] }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "release-v0.9.4" }
datalog = { package = "pallet-robonomics-datalog", path = "..", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-system/std",
    "frame-support/std",
    "datalog/std",
    "xcm/std",
]
