[package]
name = "localnet"
description = "Robonomics local network spawner based on ZombieNet SDK."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "localnet"
path = "src/main.rs"

[dependencies]
zombienet-sdk.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
colored.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
subxt.workspace = true
subxt-signer.workspace = true
chrono.workspace = true
log.workspace = true
env_logger.workspace = true
futures.workspace = true
