[package]
name = "substrate-ros-robonomics"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
log = "0.4"
bs58 = "0.2"
rosrust = "0.8"
futures-preview = { version = "0.3.0-alpha.19" }
msgs = { package = "substrate-ros-msgs", path = "../msgs" }
node-runtime = { path = "../../node/runtime" }
robonomics-liability = { path = "./liability" }
system = { package = "srml-system", git = "https://github.com/paritytech/substrate" }
balances = { package = "srml-balances", git = "https://github.com/paritytech/substrate" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate" }
sr-primitives = { git = "https://github.com/paritytech/substrate" }
transaction-pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate" }
