[package]
name = "robonet"
description = "Robonomics local network spawner based on ZombieNet SDK."
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "robonet"
path = "src/main.rs"

[build-dependencies]
robonomics-metadata = { path = "../robonomics-metadata" }

[dependencies]
zombienet-sdk.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
colored.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
subxt.workspace = true
subxt-signer.workspace = true
chrono.workspace = true
log.workspace = true
env_logger.workspace = true
futures.workspace = true

# Integration test dependencies
libcps = { path = "../libcps", default-features = false }
parity-scale-codec.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
hex.workspace = true
secp256k1 = "0.28"
