[package]
name = "robonomics-protocol"
description = "Robonomics Network protocol library."
version = "0.4.1"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3", features = ["derive"] }
substrate-subxt = "0.6"
sp-core = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
pallet-indices = "2.0.0-alpha.6"
derive_more = "0.99"
futures-timer = "3.0"
futures = "0.3.4"
bincode = "1.2"
libp2p = "0.18.1"
log = "0.4"
hex = "0.4"
