[package]
name = "robonomics-protocol"
description = "Robonomics Network protocol library."
version = "0.7.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.5", features = ["derive"] }
derive_more = "0.99.11"
futures-timer = "3.0.2"
substrate-subxt = "0.13.0"
substrate-subxt-proc-macro = "0.13.0"
pallet-indices = "2.0.0"
sp-runtime = "2.0.0"
sp-core = "2.0.0"
libp2p = "0.31.2"
futures = "0.3.8"
bincode = "1.3.1"
log = "0.4.11"
