[package]
name = "pallet-robonomics-launch-xcm"
description = "XCM extension for robot launch Substrate runtime module"
version = "0.1.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false , branch = "rococo-v1" }
launch = { package = "pallet-robonomics-launch", path = "..", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "frame-system/std",
    "frame-support/std",
    "launch/std",
    "xcm/std",
]
