[package]
name = "robonomics-request-response-example"
version = "0.1.0"
authors = ["am <yamukha@ukr.net>"]
edition = "2021"

[dependencies]
bincode = "1.3.3"
futures = "0.3.15"
libp2p = " 0.49"
rust-base58 = "0.0.4"
robonomics-protocol = { path = "../.." }
tokio = { version = "1", features = ["full"] }
