[package]
name = "robonomics-request-response-example"
version = "0.1.0"
authors = ["am <yamukha@ukr.net>"]
edition = "2018"

[dependencies]
async-std ="1.9.0"
libp2p = " 0.38.0"
libp2prs-runtime = {  version = "0.3.0" }
libp2p-core = "0.28.3"
libp2p-request-response = "0.11.0"
libp2p-noise = "0.31.0"
libp2p-swarm = "0.29.0"
libp2p-yamux = "0.32.0"
libp2p-tcp = "0.28.0"
rust-base58  = "0.0.4"
robonomics-protocol = { path = "../.." }
