name: Base checks
on:
  push:
    branches:
    - '**'
    tags-ignore:
    - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  compile-and-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install deps
      run: |
        sudo apt -y install protobuf-compiler pkg-config
        if ! command -v sccache; then
            cargo install sccache --locked
        fi
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_CACHE_SIZE=100G" >> $GITHUB_ENV

    - name: Check all features compilation
      run: cargo check --verbose --features runtime-benchmarks --locked
