name: Build Benchmarks 
permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
    branches:
    - 'feat/*'
    - 'fix/*'
    - 'release/*'
  workflow_call:
    outputs:
      status:
        description: "Status of benchmark build"
        value: ${{ jobs.build-benchmarks.outputs.status }}

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build-benchmarks:
    needs: tests
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt -y install pkg-config protobuf-compiler

    - name: Install solc
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum -y
        sudo apt update
        sudo apt -y install solc

    - name: Install resolc stub
      run: |
        sudo cp ./scripts/resolc /usr/local/bin/resolc
        sudo chmod +x /usr/local/bin/resolc

    - name: Build node with runtime-benchmarks
      run: cargo build --features runtime-benchmarks --profile production --locked

    - name: Upload benchmark binary
      uses: actions/upload-artifact@v4
      with:
        name: robonomics-benchmarks
        path: target/production/robonomics
