name: Tests
permissions:
  contents: read

on:
  push:
    branches:
    - 'feat/*'
    - 'fix/*'
    - 'release/*'
  workflow_call:
    outputs:
      status:
        description: "Status of the tests"
        value: ${{ jobs.tests.outputs.status }}

jobs:
  static-checks:
    uses: ./.github/workflows/static.yml

  tests:
    needs: static-checks
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install deps
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum -y
        sudo apt update
        sudo apt -y install pkg-config protobuf-compiler solc
        sudo cp ./scripts/resolc /usr/local/bin/resolc

    - name: Build runtime with benchmarks
      run: cargo build -p robonomics-runtime --features runtime-benchmarks --locked

    - name: Run all workspace tests
      run: cargo test --workspace --locked
