name: Tests
permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
    branches:
    - 'feat/*'
    - 'fix/*'
    - 'release/*'
  workflow_call:
    outputs:
      status:
        description: "Status of the tests"
        value: ${{ jobs.tests.outputs.status }}

jobs:
  static-checks:
    uses: ./.github/workflows/static.yml

  tests:
    needs: static-checks
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install deps
      run: |
        sudo apt update
        sudo apt -y install pkg-config protobuf-compiler

    - name: Run all tests
      run: cargo test --workspace --locked

  build-runtime-benchmarks:
    needs: static-checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt -y install pkg-config protobuf-compiler

    - name: Install solc
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum -y
        sudo apt update
        sudo apt -y install solc

    - name: Install resolc stub
      run: |
        sudo cp ./scripts/resolc /usr/local/bin/resolc
        sudo chmod +x /usr/local/bin/resolc

    - name: Build node with runtime-benchmarks
      run: cargo build --features runtime-benchmarks --profile production --locked

    - name: Upload benchmark binary
      uses: actions/upload-artifact@v4
      with:
        name: robonomics-benchmarks
        # Binary name is defined in Cargo.toml [[bin]] section
        path: target/production/robonomics
