name: Tests
on:
  push:
    branches:
    - 'feat/*'
    - 'fix/*'
    tags-ignore:
    - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
  workflow_call:
    outputs:
      test_status:
        description: "Status of the tests"
        value: ${{ jobs.check-and-tests.outputs.status }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}--${{ inputs.build_script }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  static-checks:
    uses: ./.github/workflows/static.yml

  checks-and-tests:
    needs: static-checks
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Install deps
      run: |
        sudo apt -y install protobuf-compiler pkg-config
        if ! command -v sccache; then
            cargo install sccache --locked
        fi
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_CACHE_SIZE=100G" >> $GITHUB_ENV

    - name: Check all features compilation
      run: cargo check --verbose --features runtime-benchmarks --locked

    - name: Run all tests
      run: cargo test --features runtime-benchmarks --locked
