[package]
name = "pallet-robonomics-liability"
description = "Robonomics Network Robot Liability Substrate runtime module"
version = "0.4.0"
authors = ["Airalab <research@aira.life>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

[dev-dependencies]
base58 = "0.1.0"
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" } 
node-primitives = { path = "../../../bin/node/primitives" }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-arithmetic/std",
    "frame-system/std",
    "frame-support/std",
]
